// All 39 main-flow screens (docs/flow-index.md), in order. Used by the dev
// gallery (/dev/screens) and scripts/shots.config.ts.

export type ScreenInfo = { id: string; title: string };

export const SCREEN_LIST: ScreenInfo[] = [
  { id: "01-01", title: "Landing / Sign in" },
  { id: "01-02", title: "Create home (colour blocks)" },
  { id: "01-03", title: "Create home · song playing (mini player)" },
  { id: "02-01", title: "Remix 1 · Pick a song" },
  { id: "02-02", title: "Remix 2 · …but make it" },
  { id: "02-03", title: "Cover 1 · Pick a song" },
  { id: "02-04", title: "Cover 2 · …sung by" },
  { id: "02-05", title: "Rewrite 1 · Pick a song" },
  { id: "02-06", title: "Rewrite 2 · …but it’s about" },
  { id: "02-07", title: "Something new · Describe it" },
  { id: "02-08", title: "Something new · after tapping the box" },
  { id: "03-01", title: "Generating · Remix" },
  { id: "03-02", title: "Generating · Cover" },
  { id: "03-03", title: "Generating · Rewrite" },
  { id: "03-04", title: "Generating · Vibe" },
  { id: "03-05", title: "Player · creator" },
  { id: "03-06", title: "Share sheet" },
  { id: "04-01", title: "Remix · …but make it" },
  { id: "04-02", title: "Cover · …sung by" },
  { id: "04-03", title: "Rewrite · …but it’s about" },
  { id: "04-04", title: "Vibe · describe the change" },
  { id: "04-05", title: "Vibe · after tapping the box" },
  { id: "05-01", title: "Player · recipient, not signed in" },
  { id: "05-02", title: "Remix · …but make it" },
  { id: "05-03", title: "Cover · …sung by" },
  { id: "05-04", title: "Rewrite · …but it’s about" },
  { id: "05-05", title: "Vibe · describe the change" },
  { id: "05-06", title: "Vibe · after tapping the box" },
  { id: "05-07", title: "Share sheet · recipient" },
  { id: "06-01", title: "Generating · Remix" },
  { id: "06-02", title: "Generating · Cover" },
  { id: "06-03", title: "Generating · Rewrite" },
  { id: "06-04", title: "Generating · Vibe" },
  { id: "06-05", title: "Player · recipient’s remix, not signed in" },
  { id: "06-06", title: "Send to Ali · sign in with Spotify" },
  { id: "06-07", title: "Back from Spotify · saved, share sheet already open" },
  { id: "06-08", title: "Signed in · their remix on the creator player" },
  { id: "07-01", title: "Library" },
  { id: "07-02", title: "Library · song playing (mini player)" },
];
