// Generated by scripts/persona-tastes.ts (pnpm personas:tastes) — edit the
// lists there and re-run; don't edit by hand. Derek's and Candice's Spotify
// tastes: real track/artist ids, album covers and artist photos (Spotify CDN).
import type { SpotifyTaste } from "../types/taste";

export const DEREK_TASTE: SpotifyTaste = {
  "topTracks": [
    {
      "id": "0Ftrkz2waaHcjKb4qYvLmz",
      "name": "Delilah (pull me out of this)",
      "artists": [
        "Fred again..",
        "Delilah Montagu"
      ],
      "artist": "Fred again..",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02c652ae235973f4731ec6ac50"
    },
    {
      "id": "51ODNNDZm21HU7wI7cccRr",
      "name": "Latch",
      "artists": [
        "Disclosure",
        "Sam Smith"
      ],
      "artist": "Disclosure",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02786201dca187d2b0c956c24b"
    },
    {
      "id": "5FVd6KXrgO9B3JPmC8OPst",
      "name": "Do I Wanna Know?",
      "artists": [
        "Arctic Monkeys"
      ],
      "artist": "Arctic Monkeys",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e024ae1c4c5c45aabe565499163"
    },
    {
      "id": "79Jl8KMvmnXedTjjW6pJan",
      "name": "Gosh",
      "artists": [
        "Jamie xx",
        "MC Moose"
      ],
      "artist": "Jamie xx",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e023b104b3cfcf52e380e90254d"
    },
    {
      "id": "35KiiILklye1JRRctaLUb4",
      "name": "Holocene",
      "artists": [
        "Bon Iver"
      ],
      "artist": "Bon Iver",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e024b6b1547455bbecb9f6bba64"
    },
    {
      "id": "5kadOt1O3LrIV46dns9v7u",
      "name": "Archangel",
      "artists": [
        "Burial"
      ],
      "artist": "Burial",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e020ea5498497e5bdcdb59a687a"
    },
    {
      "id": "7cucVWdmNeaPJuo7WkxaZ8",
      "name": "Boys in the Better Land",
      "artists": [
        "Fontaines D.C."
      ],
      "artist": "Fontaines D.C.",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e0241097c26aa8fd44a2986ad26"
    },
    {
      "id": "1t0Jmqg1pKVBbxjQFZebeR",
      "name": "Marea (we’ve lost dancing)",
      "artists": [
        "Fred again..",
        "The Blessed Madonna"
      ],
      "artist": "Fred again..",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02134819c325395725c3d2c612"
    },
    {
      "id": "0BxE4FqsDD1Ot4YuBXwAPp",
      "name": "505",
      "artists": [
        "Arctic Monkeys"
      ],
      "artist": "Arctic Monkeys",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02b1f8da74f225fa1225cdface"
    },
    {
      "id": "1jy7SkRcmBCTcv4ZMtwz29",
      "name": "Loud Places",
      "artists": [
        "Jamie xx",
        "Romy"
      ],
      "artist": "Jamie xx",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e023b104b3cfcf52e380e90254d"
    },
    {
      "id": "3B3eOgLJSqPEA0RfboIQVM",
      "name": "Skinny Love",
      "artists": [
        "Bon Iver"
      ],
      "artist": "Bon Iver",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02bf7c317a63c4f128b8823406"
    },
    {
      "id": "7ANO3LRdvefIongRYm5Smz",
      "name": "White Noise",
      "artists": [
        "Disclosure",
        "AlunaGeorge"
      ],
      "artist": "Disclosure",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02d3462d1395189dc76a326031"
    },
    {
      "id": "0VjIjW4GlUZAMYd2vXMi3b",
      "name": "Blinding Lights",
      "artists": [
        "The Weeknd"
      ],
      "artist": "The Weeknd",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e028863bc11d2aa12b54f5aeb36"
    },
    {
      "id": "09ttHg3ZNVgDlYBZa1ZBw0",
      "name": "Starburster",
      "artists": [
        "Fontaines D.C."
      ],
      "artist": "Fontaines D.C.",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02f69e28716be1331924f25f2e"
    },
    {
      "id": "629DixmZGHc7ILtEntuiWE",
      "name": "LUNCH",
      "artists": [
        "Billie Eilish"
      ],
      "artist": "Billie Eilish",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e0271d62ea7ea8a5be92d3c1f62"
    },
    {
      "id": "0wPfUQUkWcguy2iUH0BWOT",
      "name": "Baby",
      "artists": [
        "Four Tet"
      ],
      "artist": "Four Tet",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02210e19d835bb0af6620256cf"
    },
    {
      "id": "2fyIS6GXMgUcSv4oejx63f",
      "name": "Mardy Bum",
      "artists": [
        "Arctic Monkeys"
      ],
      "artist": "Arctic Monkeys",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e026b3fa88bdd4af566fbbf2bbf"
    },
    {
      "id": "0R0f8yu4ERU0xFbVFLoNoJ",
      "name": "Untrue",
      "artists": [
        "Burial"
      ],
      "artist": "Burial",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e020ea5498497e5bdcdb59a687a"
    },
    {
      "id": "1GfBLbAhZUWdseuDqhocmn",
      "name": "Rumble",
      "artists": [
        "Fred again..",
        "Skrillex",
        "Flowdan"
      ],
      "artist": "Fred again..",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02222c6653177eeab770765d50"
    },
    {
      "id": "0fiTN2N5HEIefAHtm00vYG",
      "name": "Wildfire",
      "artists": [
        "SBTRKT",
        "Little Dragon"
      ],
      "artist": "SBTRKT",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02237c526972e6d34ece02d290"
    }
  ],
  "topArtists": [
    {
      "id": "4oLeXFyACqeem2VImYeBFe",
      "name": "Fred again..",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174f760292919aee89e58d943d9"
    },
    {
      "id": "7Ln80lUS6He07XvHI8qqHH",
      "name": "Arctic Monkeys",
      "imageUrl": "https://i.scdn.co/image/ab676161000051747da39dea0a72f581535fb11f"
    },
    {
      "id": "6nS5roXSAGhTGr34W6n7Et",
      "name": "Disclosure",
      "imageUrl": "https://i.scdn.co/image/ab676161000051740b084ede947f009beade9a6a"
    },
    {
      "id": "7A0awCXkE1FtSU8B0qwOJQ",
      "name": "Jamie xx",
      "imageUrl": "https://i.scdn.co/image/ab676161000051745b2ba819fa89b17d6ae81567"
    },
    {
      "id": "4LEiUm1SRbFMgfqnQTwUbQ",
      "name": "Bon Iver",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174fa1d9471f2a10a3a5da1a646"
    },
    {
      "id": "0uCCBpmg6MrPb1KY2msceF",
      "name": "Burial",
      "imageUrl": "https://i.scdn.co/image/ab676161000051744be7334b7aed9ca32a732aeb"
    },
    {
      "id": "3SXwqSqAoBz9WCI9PDQzY6",
      "name": "Fontaines D.C.",
      "imageUrl": "https://i.scdn.co/image/ab6761610000517450d562d05673af1ca1380a07"
    },
    {
      "id": "1Xyo4u8uXC1ZmMpatF05PJ",
      "name": "The Weeknd",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174c1719ac9e6a75c1c25835018"
    },
    {
      "id": "6qqNVTkY8uBg9cP3Jd7DAH",
      "name": "Billie Eilish",
      "imageUrl": "https://i.scdn.co/image/ab676161000051744a21b4760d2ecb7b0dcdc8da"
    },
    {
      "id": "7Eu1txygG6nJttLHbZdQOh",
      "name": "Four Tet",
      "imageUrl": "https://i.scdn.co/image/ab6761610000517421c0ea7fc21ab3038d111ec2"
    }
  ],
  "genres": [
    "uk garage",
    "electronic",
    "house",
    "indie rock",
    "indie folk"
  ]
};

export const CANDICE_TASTE: SpotifyTaste = {
  "topTracks": [
    {
      "id": "3OHfY25tqY28d16oZczHc8",
      "name": "Kill Bill",
      "artists": [
        "SZA"
      ],
      "artist": "SZA",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02bc18bdade69ec5ef0bb25b17"
    },
    {
      "id": "5YbPxJwPfrj7uswNwoF1pJ",
      "name": "Last Last",
      "artists": [
        "Burna Boy"
      ],
      "artist": "Burna Boy",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02d98e997eaad5f503b9e1f2f2"
    },
    {
      "id": "6VBhH7CyP56BXjp8VsDFPZ",
      "name": "Kesariya",
      "artists": [
        "Arijit Singh",
        "Pritam",
        "Amitabh Bhattacharya"
      ],
      "artist": "Arijit Singh",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02f9de0806dd65b1d5e15cefd1"
    },
    {
      "id": "2qSkIjg1o9h3YT9RAgYN75",
      "name": "Espresso",
      "artists": [
        "Sabrina Carpenter"
      ],
      "artist": "Sabrina Carpenter",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02659cd4673230913b3918e0d5"
    },
    {
      "id": "1BxfuPKGuaTgP7aM0Bbdwr",
      "name": "Cruel Summer",
      "artists": [
        "Taylor Swift"
      ],
      "artist": "Taylor Swift",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02e787cffec20aa2a396a61647"
    },
    {
      "id": "2mzM4Y0Rnx2BDZqRnhQ5Q6",
      "name": "Free Mind",
      "artists": [
        "Tems"
      ],
      "artist": "Tems",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e020ab4d3e1c0b5c5e453287a4c"
    },
    {
      "id": "39LLxExYz6ewLAcYrzQQyP",
      "name": "Levitating",
      "artists": [
        "Dua Lipa"
      ],
      "artist": "Dua Lipa",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02c88bae7846e62a8ba59ee0bd"
    },
    {
      "id": "0XwRlvv3KlOu4HWlOH34XG",
      "name": "Lover",
      "artists": [
        "Diljit Dosanjh"
      ],
      "artist": "Diljit Dosanjh",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02ef759d4ae310020a06939e99"
    },
    {
      "id": "4ZtFanR9U6ndgddUvNcjcG",
      "name": "good 4 u",
      "artists": [
        "Olivia Rodrigo"
      ],
      "artist": "Olivia Rodrigo",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02a91c10fe9472d9bd89802e5a"
    },
    {
      "id": "4iZ4pt7kvcaH6Yo8UoZ4s2",
      "name": "Snooze",
      "artists": [
        "SZA"
      ],
      "artist": "SZA",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02bc18bdade69ec5ef0bb25b17"
    },
    {
      "id": "56zZ48jdyY2oDXHVnwg5Di",
      "name": "Tum Hi Ho",
      "artists": [
        "Arijit Singh",
        "Mithoon"
      ],
      "artist": "Arijit Singh",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e026404721c1943d5069f0805f3"
    },
    {
      "id": "5FG7Tl93LdH117jEKYl3Cm",
      "name": "Essence",
      "artists": [
        "Wizkid",
        "Tems"
      ],
      "artist": "Wizkid",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02b5b1023769a6bf19b14d66ab"
    },
    {
      "id": "5N3hjp1WNayUPZrA8kJmJP",
      "name": "Please Please Please",
      "artists": [
        "Sabrina Carpenter"
      ],
      "artist": "Sabrina Carpenter",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02de84adf0e48248ea2d769c3e"
    },
    {
      "id": "0V3wPSX9ygBnCm8psDIegu",
      "name": "Anti-Hero",
      "artists": [
        "Taylor Swift"
      ],
      "artist": "Taylor Swift",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02bb54dde68cd23e2a268ae0f5"
    },
    {
      "id": "6D8y7Bck8h11byRY88Pt2z",
      "name": "Houdini",
      "artists": [
        "Dua Lipa"
      ],
      "artist": "Dua Lipa",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e022f8790ed72296c2614607575"
    },
    {
      "id": "4RoKNqyZ9622tcAeNPNv5k",
      "name": "City Boys",
      "artists": [
        "Burna Boy"
      ],
      "artist": "Burna Boy",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e028ee04947c92f4eb051139cd9"
    },
    {
      "id": "4XxfOvudrnBRdlgzEaq1sd",
      "name": "Born to Shine",
      "artists": [
        "Diljit Dosanjh"
      ],
      "artist": "Diljit Dosanjh",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02e62ca3548e739bd85eebbbc9"
    },
    {
      "id": "5wANPM4fQCJwkGd4rN57mH",
      "name": "drivers license",
      "artists": [
        "Olivia Rodrigo"
      ],
      "artist": "Olivia Rodrigo",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02a91c10fe9472d9bd89802e5a"
    },
    {
      "id": "6AI3ezQ4o3HUoP6Dhudph3",
      "name": "Not Like Us",
      "artists": [
        "Kendrick Lamar"
      ],
      "artist": "Kendrick Lamar",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e021ea0c62b2339cbf493a999ad"
    },
    {
      "id": "1bjeWoagtHmUKputLVyDxQ",
      "name": "Saturn",
      "artists": [
        "SZA"
      ],
      "artist": "SZA",
      "imageUrl": "https://i.scdn.co/image/ab67616d00001e02358f9708c2cc44b153577238"
    }
  ],
  "topArtists": [
    {
      "id": "7tYKF4w9nC0nq9CsPZTHyP",
      "name": "SZA",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174fd0a9fb6c252a3ba44079acf"
    },
    {
      "id": "06HL4z0CvFAxyc27GXpf02",
      "name": "Taylor Swift",
      "imageUrl": "https://i.scdn.co/image/ab6761610000517412184bdd29403de54cb9d9c7"
    },
    {
      "id": "4YRxDV8wJFPHPTeXepOstw",
      "name": "Arijit Singh",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174adfb0b2df04b77e43b5f7375"
    },
    {
      "id": "3wcj11K77LjEY1PkEazffa",
      "name": "Burna Boy",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174b4e44d0f4e3e47af2cf06f3f"
    },
    {
      "id": "74KM79TiuVKeVCqs8QtB0B",
      "name": "Sabrina Carpenter",
      "imageUrl": "https://i.scdn.co/image/ab6761610000517478e45cfa4697ce3c437cb455"
    },
    {
      "id": "6M2wZ9GZgrQXHCFfjv46we",
      "name": "Dua Lipa",
      "imageUrl": "https://i.scdn.co/image/ab676161000051740c68f6c95232e716f0abee8d"
    },
    {
      "id": "687cZJR45JO7jhk1LHIbgq",
      "name": "Tems",
      "imageUrl": "https://i.scdn.co/image/ab6761610000517422d7d6f8981c7a27bf68a382"
    },
    {
      "id": "2FKWNmZWDBZR4dE5KX4plR",
      "name": "Diljit Dosanjh",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174fc043bea91ac91c222d235c9"
    },
    {
      "id": "1McMsnEElThX1knmY4oliG",
      "name": "Olivia Rodrigo",
      "imageUrl": "https://i.scdn.co/image/ab67616100005174b14eb4dcfd2f3858bed06e44"
    },
    {
      "id": "2YZyLoL8N0Wb9xBt1NhZWg",
      "name": "Kendrick Lamar",
      "imageUrl": "https://i.scdn.co/image/ab6761610000517439ba6dcd4355c03de0b50918"
    }
  ],
  "genres": [
    "pop",
    "r&b",
    "afrobeats",
    "filmi",
    "punjabi pop"
  ]
};
