// Generated by scripts/starter-artwork.ts (pnpm artwork:starters); don't edit
// by hand. Derek's and Candice's starter tracks' album art (Supabase Storage,
// starters/…), by slug. Set at every demo reset; never deleted by the app.
export const STARTER_ARTWORK: Record<string, string> = {};
