// Generated by scripts/starter-artwork.ts (pnpm artwork:starters); don't edit
// by hand. Derek's and Candice's starter tracks' album art (Supabase Storage,
// starters/…), by slug. Set at every demo reset; never deleted by the app.
export const STARTER_ARTWORK: Record<string, string> = {
  "derek-latch-weeknd": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/derek-latch-weeknd-669c4a0c.jpg",
  "derek-wanna-know-electronic": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/derek-wanna-know-electronic-188e78c8.jpg",
  "derek-wanna-know-pop-punk": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/derek-wanna-know-pop-punk-7ec11925.jpg",
  "derek-holocene-lofi": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/derek-holocene-lofi-a444cd21.jpg",
  "derek-505-best-friends": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/derek-505-best-friends-78157b07.jpg",
  "derek-night-bus-garage": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/derek-night-bus-garage-8928cb41.jpg",
  "candice-kill-bill-afrobeats": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/candice-kill-bill-afrobeats-39c7c9fa.jpg",
  "candice-kill-bill-arijit": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/candice-kill-bill-arijit-85ebf689.jpg",
  "candice-espresso-disco": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/candice-espresso-disco-50f1f044.jpg",
  "candice-cruel-summer-london": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/candice-cruel-summer-london-34d20f98.jpg",
  "candice-snooze-first-dates": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/candice-snooze-first-dates-3a6924d7.jpg",
  "candice-lagos-ballad": "https://iyvkdwkdzcridtiioofc.supabase.co/storage/v1/object/public/artwork/starters/candice-lagos-ballad-c5798ad8.jpg",
};
