// pnpm artwork:starters [slug …] — makes the album art for Derek's and
// Candice's starter tracks with the same prompts and models as a real make
// (lib/server/artwork/), stores it in Supabase Storage under starters/ and
// writes lib/config/starter-artwork.ts. Without slugs it only makes the
// missing ones; name slugs to remake those (the old images stay in the
// bucket). Review the images, then commit the file. Needs PRODIA_TOKEN,
// SUPABASE_URL, SUPABASE_SECRET_KEY and DATABASE_URL in .env.local.
import { config } from "dotenv";
import { writeFile } from "node:fs/promises";

config({ path: ".env.local", quiet: true });

async function main() {
  // After the env is loaded: these read it at import.
  const { PERSONAS } = await import("../lib/config/personas");
  const { STARTER_ARTWORK } = await import("../lib/config/starter-artwork");
  const { starterRows } = await import("../lib/server/auth/personas");
  const { renderArtwork } = await import("../lib/server/artwork");
  const { upload } = await import("../lib/server/artwork/storage");

  const only = process.argv.slice(2);
  const rows = PERSONAS.flatMap((p) => starterRows(p, Date.now()));
  const unknown = only.filter((s) => !rows.some((r) => r.slug === s));
  if (unknown.length) throw new Error(`Not a starter slug: ${unknown.join(", ")}`);

  const art: Record<string, string> = { ...STARTER_ARTWORK };
  for (const r of rows) {
    if (only.length ? !only.includes(r.slug) : art[r.slug]) continue;
    const started = Date.now();
    const jpeg = await renderArtwork({ id: r.slug, mode: r.mode, title: r.title, generationInput: r.generationInput });
    art[r.slug] = await upload(`starters/${r.slug}-${crypto.randomUUID().slice(0, 8)}.jpg`, jpeg, "image/jpeg");
    console.log(`${r.slug} (${r.mode}): ${Date.now() - started} ms → ${art[r.slug]}`);
  }

  const entries = rows.filter((r) => art[r.slug]).map((r) => `  ${JSON.stringify(r.slug)}: ${JSON.stringify(art[r.slug])},`);
  const out = `// Generated by scripts/starter-artwork.ts (pnpm artwork:starters); don't edit
// by hand. Derek's and Candice's starter tracks' album art (Supabase Storage,
// starters/…), by slug. Set at every demo reset; never deleted by the app.
export const STARTER_ARTWORK: Record<string, string> = {${entries.length ? `\n${entries.join("\n")}\n` : ""}};
`;
  await writeFile("lib/config/starter-artwork.ts", out);
  console.log(`Wrote lib/config/starter-artwork.ts: ${entries.length} of ${rows.length} starters have art`);
}

main().then(
  () => process.exit(0),
  (err) => {
    console.error(err);
    process.exit(1);
  },
);
